'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { useEffect } from 'react'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    console.log(2222)
  }, [])
  return (
    <html lang='en'>
      {/* className={inter.className} */}
      <body>{children}</body>
    </html>
  )
}
